import streamlit as st
import pandas as pd
from model import predict

# --- Page Configuration ---
st.set_page_config(
    page_title="AI vs. Human Text Detector",
    page_icon="🤖",
    layout="centered",
    initial_sidebar_state="auto"
)

# --- UI Elements ---
st.title("🤖 AI vs. Human Text Detector")
st.subheader("Enter a piece of text to determine if it was written by a human or an AI.")

# Text area for user input
user_text = st.text_area(
    "Paste your text here:",
    height=200,
    placeholder="For example: 'The quick brown fox jumps over the lazy dog.'"
)

# Classify button
if st.button("Classify Text"):
    if user_text:
        # --- Prediction Logic ---
        with st.spinner("Analyzing the text..."):
            try:
                # Get the prediction from the model (DUMMY DATA)
                # prediction_probs = predict(user_text)
                prediction_probs = predict(user_text)
                
                # --- Display Results ---
                st.subheader("Analysis Complete")
                
                # Display percentages in columns
                col1, col2 = st.columns(2)
                with col1:
                    human_percentage = prediction_probs['Human'] * 100
                    st.metric(label="👤 Human", value=f"{human_percentage:.2f}%")
                with col2:
                    ai_percentage = prediction_probs['AI'] * 100
                    st.metric(label="🤖 AI", value=f"{ai_percentage:.2f}%")
                
                # Determine the final verdict
                verdict = "This text is most likely written by a **Human**."
                if ai_percentage > human_percentage:
                    verdict = "This text is most likely generated by an **AI**."
                st.write(verdict)
                
                # --- Visualization ---
                st.subheader("Probability Distribution")
                
                # Create a DataFrame for the bar chart
                chart_data = pd.DataFrame({
                    "Category": ["Human", "AI"],
                    "Probability": [prediction_probs['Human'], prediction_probs['AI']]
                })
                
                # Display the bar chart
                st.bar_chart(chart_data.set_index("Category"))

            except Exception as e:
                st.error(f"An error occurred during prediction: {e}")
    else:
        st.warning("Please enter some text to classify.")

# --- Information Section ---
st.info(
    "**Note:** This detector uses a general-purpose BERT model. "
    "For higher accuracy on specific types of AI-generated text, "
    "the model should be fine-tuned on a relevant dataset."
)
